[project]
name = "payslips-scraping"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.1.0",
    "ruff>=0.11.6",
    "selenium>=4.31.0",
]
